fix: JWT verification issue due to JWK without alg
When using the TypeScript lambdas with core-stub they work fine, but
coming in through the orchestrator stub there are issues.

The error message contains to
```
TypeError: \"alg\" argument is required when \"jwk.alg\" is not present
```

This suggests there is a difference in the signing key, which is
overridable by config coming in via the authenticationAlg parameter

This PR defaults to the signing key alg, and falls back to the alg
defined as a parameter